# Generated by Django 5.2 on 2025-04-27 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('siteWeb', 'Site Web'), ('pageFacebook', 'Page Facebook')], default='siteWeb', max_length=20)),
                ('contenu', models.TextField(default='')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('publie', 'Publié')], default='brouillon', max_length=20)),
                ('date_planifiee', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, default=None, null=True)),
                ('auteur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_auteur', to=settings.AUTH_USER_MODEL)),
                ('validateur_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_validateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='unknown', max_length=50)),
                ('url', models.FileField(upload_to='medias/')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='gestion_publications.publication')),
            ],
        ),
    ]
